name: Integration Proof Data well-governed v3, functional tests via OpenSource Standards, reusing modular workflows

env:
  NODE_VERSION: '20.x'
  WORKING_DIRECTORY: ${{ github.workspace }}  
  
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: write

on:
  push:
    branches-ignore: [ "SC-ArchDecisions-v3" ]

jobs:
  job1:
    uses:  ./.github/workflows/main-data.yml
    secrets:
      github_token: ${{ secrets.GH_ORG_SC }}

  upload:
    name: Generate Build and Fetch Artifacts
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [a, b]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - name: CheckOut repo sources and artefacts
      uses: actions/checkout@v3
      
    - name: Build core and allure reporting
      run: ./Fetch_CSV.sh --version=${{ matrix.version }} >> DataResults.csv
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: results-${{ matrix.os }}-${{ matrix.version }}
        run: |
          mkdir ./Integration_Tests
          chmod 775 -R .
          mv DataResults.csv ./Integration_Tests
        path: ./Integration_Tests

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use output from Build Artifacts and Upload
        run: |
          echo "Tests output: ${{ needs.job1.outputs.tests_output }}"
  
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut repo sources and artefacts
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: |
          echo "Generating Allure report"
          npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

  job4:
    needs: [job2, job3] 
    runs-on: ubuntu-latest
    steps:
      - name: Final Step - Summary
        run: |
          echo "All jobs completed. Summary of outputs:"
          echo "Job 2 Output: ${{ needs.job2.outputs.tests_output }}"
          echo "Allure report is available as an artifact." 

