name: Integration Proof Data well-governed v3, functional tests via OpenSource Standards, reusing modular workflows

env:
  NODE_VERSION: '20.x'
  WORKING_DIRECTORY: ${{ github.workspace }}  
  
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: write

on:
  push:
    branches-ignore: [ "SC-ArchDecisions-v3" ]

jobs:
  job1:
    uses:  ./.github/workflows/main-data.yml
  upload:
    name: Generate Build and Fetch Artifacts
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [a, b, c]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Build core and allure reporting
      run: ./Integration_Tests/Fetch_CSV.sh --version=${{ matrix.version }} > results.csv
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: results-${{ matrix.os }}-${{ matrix.version }}
        path: Integration_Tests

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use output from Build Artifacts and Upload
        run: |
          echo "Tests output: ${{ needs.job1.outputs.tests_output }}"
  
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: npx modules for output coverage reports
        run: |
          echo "Output: ${{ needs.job2.outputs.tests_output }}"
          echo "Installment of dependencies to use Allure reports and npx"
          npm install -g allure >> allure-install.txt
          npx allure run -test >> $2_allure-results.txt || 
          npx allure generate ./data/
          npx allure open ./allure-report/

      - name: Upload Allure Report
        run: |
          echo "Allure report generated and uploaded, respectively retention of reports for 5 days.
          npx allure generate ./allure-results/ --clean -o ./allure-report/
          npx allure open ./allure-report/" 

  job4:
    needs: [job2, job3] 
    runs-on: ubuntu-latest
    steps:
      - name: Final Step - Summary
        run: |
          echo "All jobs completed. Summary of outputs:"
          echo "Job 2 Output: ${{ needs.job2.outputs.tests_output }}"
          echo "Allure report is available as an artifact." 

